import type { Metadata } from 'next';
import { Inter, Poppins } from 'next/font/google';
import './globals.css';
import AuthProvider from './auth/Provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Cogniverse',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="night">
      <body className={`${inter.className} min-h-screen`}>
        <AuthProvider>
          <main className="main-background text-white relative z-50">
            {children}
          </main>
        </AuthProvider>
      </body>
    </html>
  );
}
