import type { Metadata } from 'next';
import { Inter, Poppins } from 'next/font/google';
import './globals.css';
import Image from 'next/image';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen`}>
        <main className="main-background text-white relative z-50">
          <Image
            fill
            alt="main-background"
            src={'/background-image.png'}
            priority
            className="absolute  -z-10"
          />
          {children}
        </main>
      </body>
    </html>
  );
}
